[colors]
foreground = "#dcd7ba"
background = "#1f1f28"

cursor_bg = "#c8c093"
cursor_fg = "#1f1f28"
cursor_border = "#1f1f28"

selection_fg = "#c8c093"
selection_bg = "#2d4f67"

scrollbar_thumb = "#16161d"
split = "#16161d"

ansi = [
   "#090618", # black
   "#c34043", # red
   "#76946a", # green
   "#c0a36e", # yellow
   "#7e9cd8", # blue
   "#957fb8", # purple
   "#6a9589", # aqua
   "#c8c093"  # grey
]
brights = [
"#727169", "#e82424", "#98bb6c", "#e6c384", "#7fb4ca", "#938aa9", "#7aa89f", "#dcd7ba"
]

[colors.indexed]
16 = "#ffa066"
17 = "#ff5d62"

[colors.tab_bar]
background = "#1f1f28"
inactive_tab_edge = "#1f1f28"

[colors.tab_bar.active_tab]
fg_color = "#1f1f28"
bg_color = "#957fb8"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#dcd7ba"
bg_color = "#1f1f28"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#dcd7ba"
bg_color = "#1f1f28"

[colors.tab_bar.new_tab]
fg_color = "#dcd7ba"
bg_color = "#1f1f28"

[colors.tab_bar.new_tab_hover]
fg_color = "#dcd7ba"
bg_color = "#1f1f28"
intensity = "Bold"
