color = ''
project-name = 'default'
[default]
account_id = 'acct_1P5IxtIGmdpww7xP'
device_name = 'tachi-4.local'
display_name = 'ck.dev'
live_mode_api_key = 'rk_live_***********************************************************************************************LwMI'
live_mode_key_expires_at = '2024-10-01'
live_mode_pub_key = 'pk_live_51P5IxtIGmdpww7xPylRy7esznZ6CwsxYTMHnxqfDJPc3H9MSbKo4uBwFv7aK864L5SfUqogi6FlFu85oTeVA0kJC00mPN38TpP'
test_mode_api_key = 'rk_test_51P5IxtIGmdpww7xPdKNwRdLozyRfugBwJ1zrAH7xe9W8WcnPgzkOD0uR91C7gKv4WqU1t4W8tKFWMjLlP6B4OU1R00uzvHhO63'
test_mode_key_expires_at = '2024-10-01'
test_mode_pub_key = 'pk_test_51P5IxtIGmdpww7xPowV0c7W2rFfuquZUtTIbPTvZ2K8fucnePG9yLDXQ3Yl0MCl2YUJIQO7nSA7tIBaPEZVh4Bkm00W59MXIOV'

